version: '3.9'
services:
 website:
    container_name: website
    image: website
    build:
      context: .
      target: development
    ports:
      - 3000:8080
    volumes:
      - ./code/src:/home/node/src